mkdir -p "/etc/emulationstation/themes"
git clone "/etc/emulationstation/themes/simple" "https://github.com/RetroPie/es-theme-simple.git"
git clone "/etc/emulationstation/themes/pixel" "https://github.com/ehettervik/es-theme-pixel.git"
git clone "/etc/emulationstation/themes/workbench" "https://github.com/ehettervik/es-theme-workbench.git"
git clone "/etc/emulationstation/themes/io" "https://github.com/mattrixk/es-theme-io.git"
git clone "/etc/emulationstation/themes/tronkyfran" "https://github.com/HerbFargus/es-theme-tronkyfran.git"
git clone "/etc/emulationstation/themes/minimal" "https://github.com/lilbud/es-theme-minimal.git"
git clone "/etc/emulationstation/themes/snes-mini" "https://github.com/ruckage/es-theme-snes-mini.git"
git clone "/etc/emulationstation/themes/Chicuelo" "https://github.com/chicueloarcade/es-theme-Chicuelo.git"
git clone "/etc/emulationstation/themes/pii-wii" "https://github.com/waweedman/es-theme-pii-wii.git"